version: '3'

services:
  server:
    container_name: executor-component
    image: executor-component:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8081}:${PORT:-8081}
    env_file:
      - .env
    networks:
      - executor-component-network
  gemma-2b:
    container_name: gemma-2b
    image: gemma-2b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "gemma-2b"
        MODELFILE_PATH: "modelfiles/Modelfile-gemma-2b"
    ports:
      - "11434:11434"
    volumes:
      - gemma-2b_data:/root/.ollama
    networks:
      - executor-component-network
  llama3-8b:
    container_name: llama3-8b
    image: llama3-8b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "llama3-8b"
        MODELFILE_PATH: "modelfiles/Modelfile-llama3-8b"
    ports:
      - "11435:11434"
    volumes:
      - llama3-8b_data:/root/.ollama
    networks:
      - executor-component-network

volumes:
  gemma-2b_data:
  llama3-8b_data:

networks:
  executor-component-network:
    driver: bridge