version: '3'

services:
  server:
    container_name: executor-component
    image: executor-component:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8081}:${PORT:-8081}
    env_file:
      - .env
    networks:
      - executor-component-network
  gemma:
    container_name: gemma
    image: gemma:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "gemma"
        MODELFILE_PATH: "modelfiles/Modelfile-gemma"
    ports:
      - "11434:11434"
    volumes:
      - gemma_data:/root/.ollama
    networks:
      - executor-component-network

volumes:
  gemma_data:

networks:
  executor-component-network:
    driver: bridge